name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            libgl1-mesa-dev \
            libxkbcommon-dev \
            libwayland-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir dist
          cp build/app/Gamo dist/Gamo
          tar -czf Gamo-linux.tar.gz -C dist Gamo

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Gamo-linux.tar.gz
